name : my_first_pipline

on:
    push

jobs:
    My_first_job:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repo
          uses: actions/checkout@v4
            
        - name: pythaon_install
          uses: actions/setup-python@v5 
          with:
            python-version: 3.11 

        - name : update pip in github machine 
          run: python -m pip install --upgrade pip

        - name : requirements.txt file run
          run: pip install -r requirements.txt

        - name : main.py file  run
          run: python main.py

        - name : CML installation   
          uses: iterative/setup-cml@v2

        - name: Create CML report
          env:
            REPO_TOKEN: ${{ secrets.CI_SECRET_TOKEN }}
          run: 

            echo "# Test_CML Report " >> report.md
            echo "#My first graph " >> report.md
            echo '![](./one.jpg "Confusion Matrix")' >> report.md
            echo "#My second graph " >> report.md
            echo '![](./two.jpg "Confusion Matrix")' >> report.md
            
            cml comment create report.md



        




